### ISSUE TITLE
System error when compiling SCENE

### ISSUE THREAD

**Issue by fahasch** [fricas/fricas#174] opened 2024-06-04 19:44 UTC
When compiling fricas 1.3.10, I get the following error while SCENE is processed:
```   
   >> System error:
   The value
  -12295
is not of type
  (INTEGER -8192 16383)
when binding SB-ASSEM:LABEL
```
Any thoughts how this issue can be resolved?

**Comment by hebisch** [comment] 2024-06-04 21:21
On Tue, Jun 04, 2024 at 12:44:42PM -0700, fahasch wrote:
> When compiling fricas 1.3.10, I get the following error while SCENE is processed:
> ```   
>    >> System error:
>    The value
>   -12295
> is not of type
>   (INTEGER -8192 16383)
> when binding SB-ASSEM:LABEL
> ```
> Any thoughts how this issue can be resolved?

Which Lisp are you using?  "System error" is error detected by
Lisp, and this one looks like internal error in your Lisp.
Such errors may depend on exact version that you use, that is
Lisp version and kind of machine.

-- 
                              Waldek Hebisch

**Comment by fahasch** [comment] 2024-06-05 03:42
Thanks for the fast reply. I am using `SBCL 2.4.5` on a Apple M1. Compiling was working before for the system. I have downgraded to `SBCL 2.4.4` but the error persists.

**Comment by oldk1331** [comment] 2024-06-05 09:05
Thanks for reporting this issue.

I did some experiments on github CI, here are results:

This issue does not happen for x86_64 macOS.

This issue happens for sbcl-2.4.4, but not sbcl-2.4.0.

This issue happens for fricas-1.3.10 and fricas git HEAD.

So very likely, this is a SBCL regression introduced between sbcl-2.4.0 and sbcl-2.4.4.

Since I do not have ARM Mac hardware, can you do a git bisect for SBCL to find out the faulty commit?

**Comment by hemmecke** [comment] 2024-06-06 06:47
You can try parallel build with "make -j8" (replace 8 by the number of (virtual) cores you can spare.

**Comment by oldk1331** [comment] 2024-06-06 09:04
Compiling sbcl on ARM Mac should only take 1~2 minutes, and compiling FriCAS should take around 2 minutes.

Anyway, I spent some time and use github CI to do the bisection, and the faulty commit is sbcl-2.4.3~157 https://github.com/sbcl/sbcl/commit/220f6646ba06fe2cf8a602bac75ad7a3332ae562, I'll report to sbcl devs later.

**Comment by oldk1331** [comment] 2024-06-06 23:59
Should be fixed by https://github.com/sbcl/sbcl/commit/ea93bfd66893965391c16ea2bcc291f7d9ba9579 and the two commits after it.

The affected SBCL versions are 2.4.3 ~ 2.4.5.

**Closed by oldk1331** 2024-06-06 23:59 UTC
