### ISSUE TITLE
Fricas failed to compile on msys2?

### ISSUE THREAD

**Issue by zhouxs1023** [fricas/fricas#14] opened 2020-07-31 11:08 UTC
Fricas is a good project and I like it very much！
I compile Fricas on msys2（MSYS2 MinGW 32/64-bit） following these steps:

Install autotools, automake,sbcl and so on;
git clone https://github.com/fricas/fricas.git
mkdir fricas-build
cd fricas-build
../fricas/configure  --with-lisp=sbcl --prefix=/f/bin

 not success! error as below:
# ../fricas/configure --with-lisp=sbcl --prefix=/f/bin
configure: loading site script /mingw32/etc/config.site
checking build system type... i686-w64-mingw32
checking host system type... i686-w64-mingw32
checking target system type... i686-w64-mingw32
checking for gmake... no
checking for make... make
GNU Make 4.3
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for touch... touch
checking for mktemp... mktemp
checking for gawk... gawk
checking for gtar... no
checking for tar... tar
checking for ranlib... ranlib
checking for ar... ar
checking for latex... no
checking for makeindex... no
checking PREGENERATED... ""
checking Lisp implementation... This is SBCL 2.0.0, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

WARNING: the Windows port is fragile, particularly for multithreaded
code.  Unfortunately, the development team currently lacks the time
and resources this platform demands.
* sbcl
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
fasl
checking dirent.h usability... yes
checking dirent.h presence... yes
checking for dirent.h... yes
checking whether closedir is declared... yes
checking whether opendir is declared... yes
checking whether readdir is declared... yes
checking whether dirfd is declared... no
checking whether fchdir is declared... no
checking signal.h usability... yes
checking signal.h presence... yes
checking for signal.h... yes
checking whether sigaction is declared... no
checking for sys/stat.h... (cached) yes
checking for unistd.h... (cached) yes
checking whether getuid is declared... no
checking whether geteuid is declared... no
checking whether getgid is declared... no
checking whether getegid is declared... no
checking whether kill is declared... no
checking winsock2.h usability... yes
checking winsock2.h presence... yes
checking for winsock2.h... yes
checking util.h usability... no
checking util.h presence... no
checking for util.h... no
checking pty.h usability... no
checking pty.h presence... no
checking for pty.h... no
checking whether openpty is declared... no
checking for openpty in -lc... no
checking for openpty in -lutil... no
checking for openpty in -lbsd... no
checking sys/wait.h usability... no
checking sys/wait.h presence... no
checking for sys/wait.h... no
checking whether fork is declared... no
configure: Superman component is disabled.
checking for X... no
configure: The Graphics and HyperDoc components are disabled.
configure: WARNING: Aldor interface will not be built.
configure: creating ./config.status
config.status: creating src/hyper/Makefile
config.status: creating src/doc/Makefile
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/lib/Makefile
config.status: creating src/lisp/Makefile
config.status: creating src/boot/Makefile
config.status: creating src/interp/Makefile
config.status: creating src/algebra/Makefile
config.status: creating src/input/Makefile
config.status: creating src/etc/Makefile
config.status: creating src/aldor/Makefile
config.status: creating src/aldor/Makefile2
config.status: creating src/aldor/Makefile3
config.status: creating contrib/emacs/Makefile
config.status: creating config/fricas_c_macros.h
config.status: config/fricas_c_macros.h is unchanged
extracting list of SPAD type definitions
Type 'make' (without quotes) to build FriCAS
Administrator@P0KCKVOC3HZFKEQ MINGW32 /f/fricas-build
# make
make: *** No rule to make target '/f/fricas-build/config.status', needed by 'Makefile'.  Stop.

Is there a wrong configuration?
Thank you in advance for your help！

**Comment by hemmecke** [comment] 2020-07-31 12:09
Hi and welcome to FriCAs,

the FriCAS project currently still prefers discussion vial the
fricas-devel mailing list.

I cannot check your problem, because I don't have Windows, but that
error sounds strange. It says

  configure: creating ./config.status

at configure time and then complains

  make: *** No rule to make target '/f/fricas-build/config.status',
needed by 'Makefile'.  Stop.

at make time. Can you check where your config.status file was created?

BTW, if I were you, I would try to compile on WSL2. That way you could
perhaps even help the FriCAS project with a report on the installation
procedure.

Ralf

**Comment by zhouxs1023** [comment] 2020-07-31 14:35
Thank you for your reply. 
At present, I use Windows 7 ，Windows7 can't use wsl2, so I want to compile in msys2, but unfortunately it can't be compiled successfully!

**Comment by hebisch** [comment] 2020-07-31 16:01
On Fri, Jul 31, 2020 at 04:09:13AM -0700, zhouxs1023 wrote:
> Fricas is a good project and I like it very much???
> I compile Fricas on msys2???MSYS2 MinGW 32/64-bit??? following these steps:
> 
> Install autotools, automake,sbcl and so on;
> git clone https://github.com/fricas/fricas.git
> mkdir fricas-build
> cd fricas-build
> ../fricas/configure  --with-lisp=sbcl --prefix=/f/bin
> 
>  not success! error as below:
> # ../fricas/configure --with-lisp=sbcl --prefix=/f/bin
<snipped things that look OK>
> configure: creating ./config.status
<snip>
> config.status: config/fricas_c_macros.h is unchanged
> extracting list of SPAD type definitions
> Type 'make' (without quotes) to build FriCAS
> Administrator@P0KCKVOC3HZFKEQ MINGW32 /f/fricas-build
> # make
> make: *** No rule to make target '/f/fricas-build/config.status', needed by 'Makefile'.  Stop.
> 
> Is there a wrong configuration?
> Thank you in advance for your help???

Dependence of 'Makefile' on 'config.status' is introduced by autoconf.
If that does not work, tell us if you could compile _any_ program
using configure?

Could you tell us what happens when above after typing 'make' you
type (in separate lines):

pwd -W
ls -l config.status
ls -l /f/fricas-build/config.status

Prime suspect is confusion due to drive letters.  Related problem
is that file names in msys and Windows may differ.  File names
depend on your configuration and only checking on your machine
can explain what happened.

BTW: Build failed before anyhing was compiled.  'configure' generates
several files, among them 'config.status' (and 'Makefile').  Generated
makefile contains dependency on 'config.status' which is intended
to essentially force re-run of 'configure' if 'configure' is
modified after 'Makefile' was generated.  This is part of general
configure machinery, present in all programs using 'configure'.
_Some_ aspect depend on FriCAS sources, but much is how you
set up mingw/msys and how autoconf (and configure) works.

-- 
                              Waldek Hebisch

**Comment by zhouxs1023** [comment] 2020-08-01 03:46
after configure, production files are as follows:
![360-167609148070113](https://user-images.githubusercontent.com/905931/89093232-fd145e80-d3ea-11ea-8c43-5357f81210b8.png)

I have tested the compiler environment and can successfully compile gmp-6.2.0;

Administrator@P0KCKVOC3HZFKEQ MINGW64 /f/fricas-build
# pwd -W
F:/fricas-build

Administrator@P0KCKVOC3HZFKEQ MINGW64 /f/fricas-build
# ls -l config.status
-rwxr-xr-x 1 Administrator None 34152 八月    1 11:10 config.status

Administrator@P0KCKVOC3HZFKEQ MINGW64 /f/fricas-build
# ls -l /f/fricas-build/config.status
-rwxr-xr-x 1 Administrator None 34152 八月    1 11:10 /f/fricas-build/config.status

**Comment by hebisch** [comment] 2020-08-01 14:17
On Fri, Jul 31, 2020 at 08:47:08PM -0700, zhouxs1023 wrote:
> after configure, production files are as follows:
> ![360-167609148070113](https://user-images.githubusercontent.com/905931/89093232-fd145e80-d3ea-11ea-8c43-5357f81210b8.png)
> 
> I have tested the compiler environment and can successfully compile gmp-6.2.0;
> 
> Administrator@P0KCKVOC3HZFKEQ MINGW64 /f/fricas-build
> # pwd -W
> F:/fricas-build
> 
> Administrator@P0KCKVOC3HZFKEQ MINGW64 /f/fricas-build
> # ls -l config.status
> -rwxr-xr-x 1 Administrator None 34152 ??????    1 11:10 config.status
> 
> Administrator@P0KCKVOC3HZFKEQ MINGW64 /f/fricas-build
> # ls -l /f/fricas-build/config.status
> -rwxr-xr-x 1 Administrator None 34152 ??????    1 11:10 /f/fricas-build/config.status
> 

It seems that make do not see that config.status and
/f/fricas-build/config.status are the same file.  Could you
try attached patch?
-- 
                              Waldek Hebisch

**Comment by oldk1331** [comment] 2021-02-23 11:46
Can you still reproduce this problem?

Which exact version of msys2 are you using?

How did you install sbcl exactly?

**Comment by oldk1331** [comment] 2021-03-03 14:12
I have just built FriCAS successfully on msys2, both 32bit and 64 bit, so I'm closing this issue.  Feel free to reopen if you still encounter problems.

I'm pointing out another problem in your configuration: you are using 32bit C compiler `i686-w64-mingw32`, but a 64bit sbcl (currently 32bit sbcl version is 1.4.14), so you'll meet another problem later.

I may add Windows build to GitHub Actions soon, and provide binary download.

**Closed by oldk1331** 2021-03-03 14:12 UTC
